before_script:
  - git clone git@gitlab.mpcdf.mpg.de:MPIBP-Hummer/Cadishi.git
  - cd Cadishi
  - export CAD_CUDA=0
  - python setup.py build_ext --inplace
  - export PYTHONPATH=`pwd`
  - cd ..

capriqorn:
  script:
    - python setup.py build_ext --inplace
    - py.test capriqorn
