package:
    name: capriqorn
    version: "1.0.0"

source:
    path: ../../

requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy
        - cython
        - h5py
        - pyyaml

    run:
        - python
        - numpy
        - scipy
        - h5py
        - pyyaml
        - setuptools

# test:
#     # Python imports
#     imports:
#         - pyfftw
#         - pyfftw.builders
#         - pyfftw.interfaces

about:
    home: https://gitlab.mpcdf.mpg.de/MPIBP-Hummer/Capriqorn
    license: tba
    summary: 'Capriqorn'
